// -*- mode: c++ -*-

#ifndef CONFIGURATION_H
#define CONFIGURATION_H

extern int KITCHENTIMER_EDIT_TRANSITION_TIMEOUT_MS;
extern int KITCHENTIMER_EDIT_HOLD_TIMEOUT_MS;
extern int KITCHENTIMER_INITIAL_EDIT_TRANSITION_TIMEOUT_MS;
extern int KITCHENTIMER_INITIAL_EDIT_HOLD_TIMEOUT_MS;
extern int KITCHENTIMER_LEAVE_EDIT_MODE_TIMEOUT_MS;
extern int KITCHENTIMER_DIGITAL_TIMER_MODE;
extern bool KITCHENTIMER_SHOW_DEBUG_OVERLAY;

#endif
