// -*- mode: c++ -*-

#ifndef CONFIGURATION_H
#define CONFIGURATION_H

extern int KITCHENTIMER_SLIDE_VIBRATION_ON_TIMEOUT;
extern int KITCHENTIMER_SLIDE_VIBRATION_SILENCE_DURATION;
extern int KITCHENTIMER_SLIDE_VIBRATION_VIBRATION_DURATION;
extern int KITCHENTIMER_ANALOG_TIMER_MAX_FOLLOW_EXTENT;
extern int KITCHENTIMER_EDIT_TRANSITION_TIMEOUT_MS;
extern int KITCHENTIMER_EDIT_HOLD_TIMEOUT_MS;
extern int KITCHENTIMER_INITIAL_EDIT_TRANSITION_TIMEOUT_MS;
extern int KITCHENTIMER_INITIAL_EDIT_HOLD_TIMEOUT_MS;
extern int KITCHENTIMER_LEAVE_EDIT_MODE_TIMEOUT_MS;
extern int KITCHENTIMER_ANALOG_TIMER_MODE;
extern int KITCHENTIMER_DIGITAL_TIMER_MODE;
extern bool KITCHENTIMER_SHOW_DEBUG_OVERLAY;
extern bool KITCHENTIMER_USE_ANALOG_TIMER_SLIDE_SOUND;
extern bool KITCHENTIMER_USE_VIBRATION;

#endif
